### ISSUE TITLE
Some errors in installation

### ISSUE THREAD

**Issue by Yangr116** [birgander2/PyRAT#29]
Thanks for your nice work!!!

But, I met some errors in the process of installation. Please see below.

`  INFO: LeeSigma cython module not found. (run build process?)
  INFO: LeeSigma2 cython module not found. (run build process?)
  INFO: N-Dimensional Beltrami cython modules not found. (run build process?)
  INFO: Bilateral module not found. (run build process?)
  INFO: SRAD cython module not found. (run build process?)
  INFO: EMDES cython module not found. (run build process?)
  INFO: IDANQ cython module not found. (run build process?)
/home/yr2/PyRAT/pyrat/viewer/Dialogs.py:251: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif pyrat.data.layers[layer].name is not '':
/home/yr2/PyRAT/pyrat/viewer/Dialogs.py:371: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if itemname[0] is 'L':
/home/yr2/PyRAT/pyrat/viewer/Dialogs.py:392: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif itemname[0] is 'D':
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import pyrat.lib.nlsar.nlsetup as nlsetup
  File "/home/yr2/PyRAT/pyrat/__init__.py", line 105, in <module>
    from . import filter
  File "/home/yr2/PyRAT/pyrat/filter/__init__.py", line 9, in <module>
    from .Spectrum import *
  File "/home/yr2/PyRAT/pyrat/filter/Spectrum.py", line 10, in <module>
    from pyrat.filter import Unweight
  File "/home/yr2/PyRAT/pyrat/filter/Unweight.py", line 2, in <module>
    matplotlib.use('Qt5Agg')
  File "/home/yr2/.conda/envs/pyrat/lib/python3.8/site-packages/matplotlib/__init__.py", line 1171, in use
    plt.switch_backend(name)
  File "/home/yr2/.conda/envs/pyrat/lib/python3.8/site-packages/matplotlib/pyplot.py", line 284, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'Qt5Agg' which requires the 'qt5' interactive framework, as 'headless' is currently running`

And, my env packages are OK. 

Looking forward to your reply, thanks!

**Comment by birgander2** [comment]
The syntax warning are puzzeling me a bit, I don't get them. Can you tell me your Python version (I use 3.7), Windows or Linux? Latest master version?

**Comment by Yangr116** [comment]
> The syntax warning are puzzeling me a bit, I don't get them. Can you tell me your Python version (I use 3.7), Windows or Linux? Latest master version?

Thanks for your quick reply.

I used python version == 3.7.1  in Linux.

 My conda list is as below:

`# packages in environment at /home/yr2/.conda/envs/jupyter:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
anyio                     2.2.0            py37h06a4308_1
argon2-cffi               20.1.0           py37h27cfd23_1
asn1crypto                1.4.0              pyh9f0ad1d_0    conda-forge
async_generator           1.10             py37h28b3542_0
attrs                     21.2.0             pyhd3eb1b0_0
babel                     2.9.1              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
blas                      1.0                         mkl
bleach                    3.3.0              pyhd3eb1b0_0
blosc                     1.21.0               h8c45485_0
boost-cpp                 1.70.0               ha2d47e9_1    conda-forge
brotli                    1.0.9                he6710b0_2
brotlipy                  0.7.0           py37h27cfd23_1003
brunsli                   0.1                  h2531618_0
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2021.5.25            h06a4308_1
cairo                     1.14.12              h8948797_3
certifi                   2020.12.5        py37h06a4308_0
cffi                      1.14.4           py37h11fe52a_0    conda-forge
chardet                   4.0.0           py37h06a4308_1003
charls                    2.2.0                h2531618_0
cloudpickle               1.6.0                      py_0
cryptography              2.5              py37hb7f436b_1    conda-forge
curl                      7.64.0               h646f8bb_0    conda-forge
cycler                    0.10.0                   py37_0
cython                    0.29.23                  pypi_0    pypi
cytoolz                   0.11.0           py37h7b6447c_0
dask-core                 2021.5.0           pyhd3eb1b0_0
dbus                      1.13.18              hb2f20db_0
decorator                 5.0.7              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
entrypoints               0.3                      py37_0
expat                     2.3.0                h2531618_2
ffmpeg                    4.0                  hcdf2ecd_0
fontconfig                2.13.1               h6c09931_0
freeglut                  3.0.0                hf484d3e_5
freetype                  2.10.4               h5ab3b9f_0
freexl                    1.0.5             h516909a_1002    conda-forge
fsspec                    0.9.0              pyhd3eb1b0_0
gdal                      2.3.2            py37h2924dbc_0
geos                      3.6.2                heeff764_2
gettext                   0.19.8.1          hf34092f_1004    conda-forge
giflib                    5.1.9                h516909a_0    conda-forge
glib                      2.66.3               h58526e2_0    conda-forge
graphite2                 1.3.14               h23475e2_0
gst-plugins-base          1.14.0               h8213a91_2
gstreamer                 1.14.0               h28cd5cc_2
h5py                      2.8.0            py37h989c5e5_3
harfbuzz                  1.8.8                hffaf4a1_0
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.2               hba1933b_1
icu                       58.2                 he6710b0_3
idna                      2.10               pyhd3eb1b0_0
imagecodecs               2021.4.28        py37h581e88b_0
imageio                   2.9.0              pyhd3eb1b0_0
importlib-metadata        3.10.0           py37h06a4308_0
importlib_metadata        3.10.0               hd3eb1b0_0
intel-openmp              2021.2.0           h06a4308_610
ipykernel                 5.3.4            py37h5ca1d4c_0
ipython                   7.22.0           py37hb070fc8_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
jasper                    2.0.14               h07fcdf6_1
jedi                      0.17.0                   py37_0
jinja2                    2.11.3             pyhd3eb1b0_0
joblib                    1.0.1              pyhd3eb1b0_0
jpeg                      9b                   h024ee3a_2
json-c                    0.13.1            hbfbb72e_1002    conda-forge
json5                     0.9.5                      py_0
jsonschema                3.2.0                      py_2
jupyter-packaging         0.7.12             pyhd3eb1b0_0
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1              pyhd8ed1ab_2    conda-forge
jupyter_core              4.7.1            py37h06a4308_0
jupyter_highlight_selected_word 0.2.0           py37h89c1867_1002    conda-forge
jupyter_latex_envs        1.4.6           pyhd8ed1ab_1002    conda-forge
jupyter_nbextensions_configurator 0.4.1            py37h89c1867_2    conda-forge
jupyter_server            1.4.1            py37h06a4308_0
jupyterlab                3.0.14             pyhd3eb1b0_1
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.4.0              pyhd3eb1b0_0
jxrlib                    1.1                  h7b6447c_2
kealib                    1.4.7                h77bc034_6
kiwisolver                1.3.1            py37h2531618_0
krb5                      1.16.3            hc83ff2d_1000    conda-forge
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.33.1               h53a641e_7
lerc                      2.2.1                h2531618_0
libaec                    1.0.4                he6710b0_1
libcurl                   7.64.0               h01ee5af_0    conda-forge
libdap4                   3.19.1               h6ec2957_0
libdeflate                1.7                  h27cfd23_5
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0
libgdal                   2.3.2                h9d4a965_0
libgfortran-ng            7.3.0                hdf63c60_0
libglib                   2.66.3               hbe7bbb4_0    conda-forge
libglu                    9.0.0                hf484d3e_1
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
libnetcdf                 4.6.1                h5e45101_3    conda-forge
libopencv                 3.4.2                hb342d67_1
libopus                   1.3.1                h7b6447c_0
libpng                    1.6.37               hbc83047_0
libpq                     10.6              h13b8bad_1000    conda-forge
libsodium                 1.0.18               h7b6447c_0
libspatialite             4.3.0a              he475c7f_19
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h2733197_1
libuuid                   1.0.3                h1bed415_2
libvpx                    1.7.0                h439df22_0
libwebp                   1.0.1                h8e7db2f_0
libxcb                    1.14                 h7b6447c_0
libxml2                   2.9.10               hb55368b_3
libxslt                   1.1.34               hc22bd24_0
libzopfli                 1.0.3                he6710b0_0
locket                    0.2.1            py37h06a4308_1
lxml                      4.6.3            py37h9120a33_0
lz4-c                     1.9.3                h2531618_0
mako                      1.1.4              pyhd3eb1b0_0
markupsafe                1.1.1            py37h14c3975_1
matplotlib                3.3.4            py37h06a4308_0
matplotlib-base           3.3.4            py37h62a2d02_0
mistune                   0.8.4           py37h14c3975_1001
mkl                       2021.2.0           h06a4308_296
mkl-service               2.3.0            py37h27cfd23_1
mkl_fft                   1.3.0            py37h42c9631_2
mkl_random                1.2.1            py37ha9443f7_2
nbclassic                 0.2.6              pyhd3eb1b0_0
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.0.7                    py37_0
nbformat                  5.1.3              pyhd3eb1b0_0
ncurses                   6.2                  he6710b0_1
nest-asyncio              1.5.1              pyhd3eb1b0_0
networkx                  2.2                      py37_1
notebook                  6.3.0            py37h06a4308_0
numexpr                   2.7.3            py37h22e1b3c_1
numpy                     1.20.1           py37h93e21f0_0
numpy-base                1.20.1           py37h7d8b39e_0
olefile                   0.46                     py37_0
opencv                    3.4.2            py37h6fd60c2_1
opencv-contrib-python     4.5.2.52                 pypi_0    pypi
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.0.2u               h7b6447c_0
packaging                 20.9               pyhd3eb1b0_0
pandas                    1.2.4            py37h2531618_0
pandoc                    2.12                 h06a4308_0
pandocfilters             1.4.3            py37h06a4308_1
parso                     0.8.2              pyhd3eb1b0_0
partd                     1.2.0              pyhd3eb1b0_0
pcre                      8.44                 he6710b0_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.2.0            py37he98fc37_0
pip                       21.0.1           py37h06a4308_0
pixman                    0.40.0               h7b6447c_0
poppler                   0.65.0               h581218d_1
poppler-data              0.4.10                        0    conda-forge
proj4                     5.0.1                h14c3975_0
prometheus_client         0.10.1             pyhd3eb1b0_0
prompt-toolkit            3.0.17             pyh06a4308_0
ptyprocess                0.7.0              pyhd3eb1b0_2
py-opencv                 3.4.2            py37hb342d67_1
pycparser                 2.20                       py_2
pygments                  2.8.1              pyhd3eb1b0_0
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.7              pyhd3eb1b0_0
pyqt                      5.9.2            py37h05f1152_2
pyrsistent                0.17.3           py37h7b6447c_0
pysocks                   1.7.1                    py37_1
python                    3.7.1             hd21baee_1001    conda-forge
python-dateutil           2.8.1              pyhd3eb1b0_0
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2021.1             pyhd3eb1b0_0
pywavelets                1.1.1            py37h7b6447c_2
pyyaml                    5.4.1            py37h27cfd23_1
pyzmq                     20.0.0           py37h2531618_1
qt                        5.9.6                h8703b6f_2
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.25.1             pyhd3eb1b0_0
scikit-image              0.18.1           py37ha9443f7_0
scikit-learn              0.24.2           py37ha9443f7_0
scipy                     1.6.2            py37had2a1c9_1
send2trash                1.5.0              pyhd3eb1b0_1
setuptools                52.0.0           py37h06a4308_0
sip                       4.19.8           py37hf484d3e_0
six                       1.15.0           py37h06a4308_0
snappy                    1.1.8                he6710b0_0
sniffio                   1.2.0            py37h06a4308_1
sqlite                    3.28.0               h8b20d00_0    conda-forge
terminado                 0.9.4            py37h06a4308_0
testpath                  0.4.4              pyhd3eb1b0_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
tifffile                  2021.4.8           pyhd3eb1b0_2
tk                        8.6.10               hbc83047_0
toolz                     0.11.1             pyhd3eb1b0_0
tornado                   6.1              py37h27cfd23_0
traitlets                 5.0.5              pyhd3eb1b0_0
typing_extensions         3.7.4.3            pyha847dfd_0
urllib3                   1.26.4             pyhd3eb1b0_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
wheel                     0.36.2             pyhd3eb1b0_0
xerces-c                  3.2.2             hea5cb30_1003    conda-forge
xz                        5.2.5                h7b6447c_0
yaml                      0.2.5                h7b6447c_0
zeromq                    4.3.4                h2531618_0
zfp                       0.5.5                h2531618_6
zipp                      3.4.1              pyhd3eb1b0_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.9                haebb681_0`

Looking forward to you new reply, thanks.
